### PR TITLE
562 fix codacy on master 1

### PR DESCRIPTION
**Pull request by ntchen**

### CODE REVIEW

**Review by smilesun — CHANGES_REQUESTED** [review]
CI is broken

**Comment by smilesun** [comment]
@ntchen https://github.com/snakemake/snakemake/issues/2607

**Comment by smilesun** [comment]
https://anaconda.org/bioconda/snakemake

**Comment by smilesun** [comment]
https://app.codacy.com/gh/marrlab/DomainLab/pullRequest?bid=39739936&prid=13402189&utm_campaign=new_commit&utm_medium=Email&utm_source=Internal&

**Comment by ntchen** [comment]
> https://app.codacy.com/gh/marrlab/DomainLab/pullRequest?bid=39739936&prid=13402189&utm_campaign=new_commit&utm_medium=Email&utm_source=Internal&

It seems that they are not new issues. The file modifications triggered a scan which resulted in the identification of these new issues. The total issues were reduced from 639 to 573.

**Comment by ntchen** [comment]
`UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:
Specifications:
  - bioconda::snakemake -> python[version='3.4.*|3.5.*|3.6.*|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0']`

**Comment by smilesun** [comment]
> `UnsatisfiableError: The following specifications were found to be incompatible with the existing python installation in your environment: Specifications:
> 
> * bioconda::snakemake -> python[version='3.4._|3.5._|3.6.*|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0']`

so we will increase the python version to 3.11, then pip should find snakemake 8.2.0

**Comment by ntchen** [comment]
> > https://app.codacy.com/gh/marrlab/DomainLab/pullRequest?bid=39739936&prid=13402189&utm_campaign=new_commit&utm_medium=Email&utm_source=Internal&
> 
> It seems that they are not new issues. The file modifications triggered a scan which resulted in the identification of these new issues. The total issues were reduced from 639 to 573.

How shall we merge it after success CI tests? It will not be fast to fix the 573 issues. We can try to adjust settings to focus on the changes made in the merge request rather than scanning all related files. But even though, I think the changed lines include a lot of other issues. is it worth overriding merge checks?

**Comment by smilesun** [comment]
> > > https://app.codacy.com/gh/marrlab/DomainLab/pullRequest?bid=39739936&prid=13402189&utm_campaign=new_commit&utm_medium=Email&utm_source=Internal&
> > 
> > 
> > It seems that they are not new issues. The file modifications triggered a scan which resulted in the identification of these new issues. The total issues were reduced from 639 to 573.
> 
> How shall we merge it after success CI tests? It will not be fast to fix the 573 issues. We can try to adjust settings to focus on the changes made in the merge request rather than scanning all related files. But even though, I think the changed lines include a lot of other issues. is it worth overriding merge checks?

some issues are not avoidable:e.g. too many arguments in a function, we could fix other issues manually though.  see my latest commits.

**Comment by smilesun** [comment]
@ntchen 

Run pip install pulp<2.8 && install snakemake==7.32.0 && sed -i '1s/^/#!\/bin\/bash -x -v\n/' run_benchmark_standalone.sh && bash -x -v run_benchmark_standalone.sh examples/benchmark/demo_shared_hyper_grid.yaml && cat zoutput/benchmarks/mnist_benchmark_grid/hyperparameters.csv && cat zoutput/benchmarks/mnist_benchmark_grid/results.csv
/home/runner/work/_temp/0e90565a-d45b-415a-9af3-e86f855f[7](https://github.com/marrlab/DomainLab/actions/runs/7551953517/job/20560015221#step:10:8)956.sh: line 1: 2.[8](https://github.com/marrlab/DomainLab/actions/runs/7551953517/job/20560015221#step:10:9): No such file or directory
Error: Process completed with exit code 1.

**Comment by ntchen** [comment]
> @ntchen
> 
> Run pip install pulp<2.8 && install snakemake==7.32.0 && sed -i '1s/^/#!/bin/bash -x -v\n/' run_benchmark_standalone.sh && bash -x -v run_benchmark_standalone.sh examples/benchmark/demo_shared_hyper_grid.yaml && cat zoutput/benchmarks/mnist_benchmark_grid/hyperparameters.csv && cat zoutput/benchmarks/mnist_benchmark_grid/results.csv /home/runner/work/_temp/0e90565a-d45b-415a-9af3-e86f855f[7](https://github.com/marrlab/DomainLab/actions/runs/7551953517/job/20560015221#step:10:8)956.sh: line 1: 2.[8](https://github.com/marrlab/DomainLab/actions/runs/7551953517/job/20560015221#step:10:9): No such file or directory Error: Process completed with exit code 1.

it should be the missing pip for snakemake. You already fixed it

**Comment by smilesun** [comment]
> > @ntchen
> > Run pip install pulp<2.8 && install snakemake==7.32.0 && sed -i '1s/^/#!/bin/bash -x -v\n/' run_benchmark_standalone.sh && bash -x -v run_benchmark_standalone.sh examples/benchmark/demo_shared_hyper_grid.yaml && cat zoutput/benchmarks/mnist_benchmark_grid/hyperparameters.csv && cat zoutput/benchmarks/mnist_benchmark_grid/results.csv /home/runner/work/_temp/0e90565a-d45b-415a-9af3-e86f855f[7](https://github.com/marrlab/DomainLab/actions/runs/7551953517/job/20560015221#step:10:8)956.sh: line 1: 2.[8](https://github.com/marrlab/DomainLab/actions/runs/7551953517/job/20560015221#step:10:9): No such file or directory Error: Process completed with exit code 1.
> 
> it should be the missing pip for snakemake. You already fixed it

not really, see the CI run result from my commit

**Pull request merged**
