### PR TITLE
Multi task support seq2seq, segmentation, rl

### PR DESCRIPTION
**Pull request by smilesun**

### CODE REVIEW

**Comment by smilesun** [comment]
@prockenschaub , we have introduced new issues into the code

https://app.codacy.com/gh/marrlab/DomainLab/pullRequest?bid=31541691&prid=10331475&utm_campaign=new_commit&utm_medium=Email&utm_source=Internal&

**Comment by prockenschaub** [comment]
Most are missing docstrings. Will add docstrings to the parts I changed later today. One was a genuine error because I needed to change something in matchdg but didn't run the tests for it. Will fix that now.

**Comment by smilesun** [comment]
@prockenschaub,  more work need to be done for matchdg, but now all checks have passed.  Ready to implement models that support other tasks on top of this branch. We might need to periodically merge master into this branch before we fix the matchdg issue so that i can be merged easily.

**Comment by smilesun** [comment]
codacy issues decreased from 36 to 21 after the lastest commit

**Pull request merged**
