### PR TITLE
fix doc fishr display

### PR DESCRIPTION
**Pull request by lisab00**
display of latex equations in doc fishr is not correct

### CODE REVIEW

**Comment by smilesun** [comment]
Hi, Lisa, I think your documentation is really high quality, but I have not the time budget yet to look at the error, this would be less prioritized then.

**Comment by agisga** [comment]
> @agisga , do you know?

No, sorry. What latex renderer is used here? Maybe it's restricted to only a subset of latex commands, since some of the simpler equations seem to be displayed fine..

**Comment by agisga** [comment]
> @agisga , do you know?

Not sure if it will fix the entire issue, but there are some `$$` symbols missing, for instance:
- " §§\theta$$ denote "
- "$$\mathcal{R}_e(\theta) be the ERM"

**Comment by lisab00** [comment]
No problem if you have no time, it's not a priority.
I already fixed the issue you mention here. 

> Not sure if it will fix the entire issue, but there are some `$$` symbols missing, for instance:
> 
> * " §§\theta$$ denote "
> * "$$\mathcal{R}_e(\theta) be the ERM"

I am just talking about the display equations (like in line 25-27 in the md file)

**Comment by agisga** [comment]
> I am just talking about the display equations (like in line 25-27 in the md file)

I'm not sure what latex renderer is being used here, but with the most common latex interpreters, if a dollar sign is missing anywhere in the document, then it can mess up the formatting everywhere in the rest of the document (like if you open an `$$` in some line but never close it, then it may be assumed that the whole rest of the document is one long equation)... I think it's like with any type of programming, a bug in one line can lead to an error in an entirely different line. So, in my opinion, I would strongly suggest that to fix the syntax everywhere, not just lines 25-27...

**Comment by lisab00** [comment]
> > I am just talking about the display equations (like in line 25-27 in the md file)
> 
> I'm not sure what latex renderer is being used here, but with the most common latex interpreters, if a dollar sign is missing anywhere in the document, then it can mess up the formatting everywhere in the rest of the document (like if you open an `$$` in some line but never close it, then it may be assumed that the whole rest of the document is one long equation)... I think it's like with any type of programming, a bug in one line can lead to an error in an entirely different line. So, in my opinion, I would strongly suggest to fix the syntax everywhere, not just lines 25-27...

Alright I understand, thank you very much! @agisga

**Comment by lisab00** [comment]
display is now fixed: https://github.com/marrlab/DomainLab/blob/lb_fix_doc_fishr/docs/docFishr.md

**Pull request merged**
