### PR TITLE
add md files with code examples to ci_run_examples.sh

### PR DESCRIPTION
**Pull request by Car-la-F**
will solve #248

### CODE REVIEW

**Comment by Car-la-F** [comment]
@smilesun 
I was wondering how the command does handle the code blocks which do not actually contain code.
Like in `docs/doc_tasks.md` there is a code block containing

```
    ── /path/to/1st_domain/folder_a
       ├── auto
       ├── hund
       ├── mensch
       ├── stuhl
       └── vogel
```

does this lead to any issue?

**Comment by smilesun** [comment]
> @smilesun I was wondering how the command does handle the code blocks which do not actually contain code. Like in `docs/doc_tasks.md` there is a code block containing
> 
> ```
>     ── /path/to/1st_domain/folder_a
>        ├── auto
>        ├── hund
>        ├── mensch
>        ├── stuhl
>        └── vogel
> ```
> 
> does this lead to any issue?

for the noncode part, we have to skip but currently i don't have a good solution in mind. If you also not, we can leave it like this maybe the best solution is to delete all non-code content inside the code quotation mark.

**Comment by Car-la-F** [comment]
@smilesun 
I read a little about code blocks in markdown files. I found out that it is possible to specify the programming language and the code block will get syntax highlights. The default is "shell", which I guess is the one we do always want to use.

Anyway, if we specify the code blocks which actually contain code and shall be executed we could specify them as shell code blocks and add this to the 
sed 's/`//g' docs/doc_examples.md > ./sh_temp.sh
such that it only finds actual code blocks.

I guess is should be possible to extract shell code blocks, isn't it?

"normal code block" -> all code block containing non code content
\`\`\`
... code ...
\`\`\`

"shell code block" -> all code blocks containing code
\`\`\`shell
... code ...
\`\`\`

**Comment by smilesun** [comment]
> @smilesun I read a little about code blocks in markdown files. I found out that it is possible to specify the programming language and the code block will get syntax highlights. The default is "shell", which I guess is the one we do always want to use.
> 
> Anyway, if we specify the code blocks which actually contain code and shall be executed we could specify them as shell code blocks and add this to the sed 's/`//g' docs/doc_examples.md > ./sh_temp.sh such that it only finds actual code blocks.
> 
> I guess is should be possible to extract shell code blocks, isn't it?
> 
> "normal code block" -> all code block containing non code content ``` ... code ... ```
> 
> "shell code block" -> all code blocks containing code ```shell ... code ... ```

@Car-la-F  Yes, i think that is a good idea! Could you make it happen?

**Comment by Car-la-F** [comment]
I hope I have found all interesting code blocks. I also added the python keyword to codeblocks where we have python code `doc_task.md` . It seems not to make a big difference in the git, but on my local interpreter I got some code highlights as it is in normal python code.

**Comment by Car-la-F** [comment]
@smilesun 
I was trying to adapt the shell comand you send to me to find the shell code blocks. 
By trying out `sed 's/`//g' docs/doc_examples.md` I observed that this comand does not just extract the code blocks, but does only remove the \` from the file. Hence the output does contain the full text, but without the quotation marks used to generate code blocks.

I searched a bit for a solution how to actually extract the code blocks, but I haven't found something until now
``

**Comment by Car-la-F** [comment]
Seems like I found something which might work:

sed -n '/```shell/,/```/ p' docs/doc_examples.md | sed '/^```/ d'

**Pull request merged**
