### PR TITLE
add slurm_id to model name as suffix Update exp_utils.py

### PR DESCRIPTION
**Pull request by smilesun**

### CODE REVIEW

**Comment by smilesun** [comment]
There seems to be a bug in branch master after fisher is merged but maybe everything will be alright.

**Comment by lisab00** [comment]
> There seems to be a bug in branch master after fisher is merged but maybe everything will be alright.

I got this error, might it have something to do with the bug, or is ist something else ? The hyperparameters sampling was successfully completed
image

**Comment by smilesun** [comment]
Just run it again

**Comment by lisab00** [comment]
I ran it again and all jobs are failing with error. But there's no error message and no log folder created

**Comment by smilesun** [comment]
Error should be in zoutput folder. I updated the benchmark documentation

**Pull request merged**
