### PR TITLE
Benchmark snakemake

### PR DESCRIPTION
**Pull request by smilesun**
It is easier for me to keep track of a branch if we have a pull request, so please ignore if the build fails at this stage.

### CODE REVIEW

**Comment by schoersch** [comment]
@smilesun Are you plannning to merge the blood cell related files to master at some point? Since the dataset is not open accessible, I think this makes no sense.
At least for the moment, I separated the two files for this benchmark on the branch `bloodcell_benchmark` (task_blood2.py and bloodcell_test.yaml)

@xinyuejohn by the reasoning above, I reverted the benchmark demo on this branch. I think the benchmark is a new feature of domainlab and therefore, the `demo_benchmark.yaml` is also
1. Referenced in the docs
2. Used for testing the benchmark
from my side.
Your changes are on the branch mentioned above.

**Comment by xinyuejohn** [comment]
@schoersch I saw the changes, thanks!

**Comment by smilesun** [comment]
@schoersch @xinyuejohn @Car-la-F 
is this branch still relevant? or shall we close it ?

**Comment by schoersch** [comment]
> @schoersch @xinyuejohn @Car-la-F is this branch still relevant? or shall we close it ?

@Car-la-F  and I moved our work to #119. Doing so, we did not moved the boxplot code, since we agreed on making the boxplots a separate issue.

**Comment by smilesun** [comment]
@xinyuejohn , i will then close this pr, if you want to merge the box plot, you can make a separate pr

**Pull request closed without merging**
