### PR TITLE
Remove unused imports

### PR DESCRIPTION
**Pull request by prockenschaub**
Removal of several unused imports as flagged by codacy (this time into the correct branch...).

### CODE REVIEW

**Comment by smilesun** [comment]
may I know why it is a pull request to merge into dev instead of master?

**Comment by aliechoes** [comment]
It is better to keep this under dev, as such modifications might change the
behavior of the code.

**Comment by prockenschaub** [comment]
Yeah I wasn't sure what your policies were on this, so I thought it more prudent to merge into dev. Happy to reopen my (now closed) first pull request that actually by default was into master.

**Comment by aliechoes** [comment]
I would suggest to keep it under dev please and thanks for contribution :)

@Xudong: can you please check whether the dev branch would work after
taking out some of the unused modules?

I initially wanted to take them out, but I was not fully sure as in those
files torch tensors or numpy array are being used

**Comment by prockenschaub** [comment]
If I understand correctly, you are unsure if files processing torch/numpy objects will still work if they don't import torch/numpy. As long as you are only operating on the objects (and functions bound to them), it shouldn't matter.  You can easily test this for example with two files: 

module.py:
```python
def custom_max(x):
    return x.max()
```

script.py:
```python
import numpy as np
from module import custom_max

np.random.seed(42)
x = np.random.uniform(size=10)
custom_max(x)
#> 0.9507143064099162
```

Still worth testing, though, to make sure I haven't removed anything vital :D

**Comment by prockenschaub** [comment]
I just realised that my changes introduce new Codacy code quality issues. It originally complained about try-except blocks where the error `e` was never used, now it continues to complain about the too general `Exception` type and the try-except-pass constructs. Any suggestions how to solve this?

P.S.: I also saw that #29 got reopened, would you like me to use that one instead. I stayed with this PR for now to keep all discussion in one place.

**Comment by smilesun** [comment]
Now codacy passed. 

@aliechoes 

1. I haven't got the point of the advantages of merging into dev, since merging small changes each time into master will be easier?

2. I will think how can we test the behavior, maybe I run the same command in two different folders on the same laptop to see if the results are the same? 

3. If we find too much work to improve the code quality of the bash files, we can move them to a separate branch.

**Comment by aliechoes** [comment]
so, in general and for further development, you want your the changes to the dev. As we are going to have version control on the master branch. This will guarantee the sanity of the master branch for the users.

**Pull request merged**
