### PR TITLE
prevent parameter doubling in benchmark yaml

### PR DESCRIPTION
**Pull request by Car-la-F**
prevent that a hyperparameter which is sampled in the sampling section was already set inside the task section or the domainlab_args section

will solve #381

### CODE REVIEW

**Comment by smilesun** [comment]
I tested, it works on my laptop, but I am not sure if it works on teh cluster, @e-dorigatti , could you help to test this branch by running hte mnist example to see if everythign can be finished?

**Comment by e-dorigatti** [comment]
> I tested, it works on my laptop, but I am not sure if it works on teh cluster, @e-dorigatti , could you help to test this branch by running hte mnist example to see if everythign can be finished?

should I run this one `benchmark_mnist_shared_hyper_grid.yaml` ?

**Comment by smilesun** [comment]
> > I tested, it works on my laptop, but I am not sure if it works on teh cluster, @e-dorigatti , could you help to test this branch by running hte mnist example to see if everythign can be finished?
> 
> should I run this one `benchmark_mnist_shared_hyper_grid.yaml` ?

yes please

**Comment by smilesun** [comment]
> > > I tested, it works on my laptop, but I am not sure if it works on teh cluster, @e-dorigatti , could you help to test this branch by running hte mnist example to see if everythign can be finished?
> > 
> > 
> > should I run this one `benchmark_mnist_shared_hyper_grid.yaml` ?
> 
> yes please

mAYBE YOU could delete all logs in slurm_logs folder in zoutput to find out if new errors occur

**Comment by e-dorigatti** [comment]
it ran successfully. do I need to do some other check to make sure that the PR worked correctly?

**Comment by smilesun** [comment]
@e-dorigatti , gr8, tks!  could you check if any errors occur in the slurm log file?

https://github.com/marrlab/DomainLab/blob/edb40ea41409acba6406128d8e0f31ae179dd07f/docs/doc_benchmark.md?plain=1#L44

**Comment by e-dorigatti** [comment]
> @e-dorigatti , gr8, tks! could you check if any errors occur in the slurm log file?
> 
> https://github.com/marrlab/DomainLab/blob/edb40ea41409acba6406128d8e0f31ae179dd07f/docs/doc_benchmark.md?plain=1#L44

is the documentation correct? do I have to run run_benchmark_slurm.sh again to check for errors? what about sh_list_error.sh ?

**Comment by smilesun** [comment]
> > @e-dorigatti , gr8, tks! could you check if any errors occur in the slurm log file?
> > https://github.com/marrlab/DomainLab/blob/edb40ea41409acba6406128d8e0f31ae179dd07f/docs/doc_benchmark.md?plain=1#L44
> 
> is the documentation correct? do I have to run run_benchmark_slurm.sh again to check for errors? what about sh_list_error.sh ?
@e-dorigatti 
Hi, 
1. docuemntation: i hope it is correct, i updated it today but if there are errors, welcome to write an issue 
2. no need to run the benchmark if you have already **on this branch** ran the benchamrk
3. sh_list_error is the link i sent to you, which will use grep to search for regular expression with "error" in the slurm_logs directory, since there might be too many files there, it is too slow to mannually check which job has an error and when that error occurs, if you have a better script, welcome to make a pull reqeust to master!

**Comment by e-dorigatti** [comment]
got it, then the documentation needs to be updated. and sh_list_error did not find any problem, so this PR looks fine

**Pull request merged**
