### PR TITLE
Add blood cell benchmark yaml

### PR DESCRIPTION
**Pull request by Car-la-F**
resolves issue #103

### CODE REVIEW

**Comment by schoersch** [comment]
see https://github.com/marrlab/DomainLab/pull/100#issuecomment-1430909795

**Comment by xinyuejohn** [comment]
Hi @smilesun @Car-la-F @schoersch @rahulbshrestha 

I have checked the dataset and also run the test round on the virtual machine.

Here are some useful information:

1) Dataset Information

	There are 3 domains in total: Matek,  MLL, Acevedo
	
	All three domains have 10 classes in common:
	
	basophil    erythroblast  metamyelocyte   neutrophil_band   promyelocyte
	eosinophil  lymphocyte_typical  monocyte    myelocyte   neutrophil_segmented
	
	Domain Matek and MLL have one more class: myeloblast
	
	For Matek, there are 18k images. Size: 345 * 345
	For MLL, there are 19k images. Size: 288 * 288
	For Acevedo, there are 14k images. Size: 250 * 250

2)  Machine information

	CPU: cores 16
	GPU: 1 Tesla T4

3) Running Speed Test

	Single run using DomainLab directly:
	For three-class classification on randomly selected 3 classes, batch size could be at most 16, and for each epoch it takes 	around 2 minutes.
	I am still testing 10-class classification now. 
	
	Run using Snakemake:
	I tested three-class classification on randomly selected 3 classes. I am still running it now.

    But the reading process in both cases takes quite a long time. Usually more than one hour. (As the figure below)
	
test_run


4) Benchmark Strategy 

	According to the previous presentation from Carla, we need to train model on two domains and test on the remaining one. And our task is multi-class classification. In our case, we need repeat this three times.
	For transforms of training data and test data, should we keep using the existing settings from DomainLab/examples/tasks/task_blood2.py?


Do you have any suggestions or ideas of next step?

**Comment by schoersch** [comment]
We have to make sure, that we run the benchmark with Python 3.9^, see #114 

@xinyuejohn I just couldn't found the `domainlab_env` on the vm to check.

**Comment by xinyuejohn** [comment]
> We have to make sure, that we run the benchmark with Python 3.9^, see #114
> 
> @xinyuejohn I just couldn't found the `domainlab_env` on the vm to check.

Rahul helped me set up this environment. But it is python 3.8. If you want to use it, you have to use: 

`source envs/domainlab_env/bin/activate`

**Comment by Car-la-F** [comment]
@smilesun,
FYI 
this is the yaml file we like to discuss with you tomorrow.

**Comment by smilesun** [comment]
> We have to make sure, that we run the benchmark with Python 3.9^, see #114
> 
> @xinyuejohn I just couldn't found the `domainlab_env` on the vm to check.

I changed the pyproject file to have python 3.9^

**Comment by smilesun** [comment]
> Hi @smilesun @Car-la-F @schoersch @rahulbshrestha
> 
> I have checked the dataset and also run the test round on the virtual machine.
> 
> Here are some useful information:
> 
> 1. Dataset Information
>    There are 3 domains in total: Matek,  MLL, Acevedo
>    All three domains have 10 classes in common:
>    basophil    erythroblast  metamyelocyte   neutrophil_band   promyelocyte
>    eosinophil  lymphocyte_typical  monocyte    myelocyte   neutrophil_segmented
>    Domain Matek and MLL have one more class: myeloblast
>    For Matek, there are 18k images. Size: 345 * 345
>    For MLL, there are 19k images. Size: 288 * 288
>    For Acevedo, there are 14k images. Size: 250 * 250
> 2. Machine information
>    CPU: cores 16
>    GPU: 1 Tesla T4
> 3. Running Speed Test
>    Single run using DomainLab directly:
>    For three-class classification on randomly selected 3 classes, batch size could be at most 16, and for each epoch it takes 	around 2 minutes.
>    I am still testing 10-class classification now.
>    Run using Snakemake:
>    I tested three-class classification on randomly selected 3 classes. I am still running it now.
>    But the reading process in both cases takes quite a long time. Usually more than one hour. (As the figure below)
> 
> test_run
> 
> 4. Benchmark Strategy
>    According to the previous presentation from Carla, we need to train model on two domains and test on the remaining one. And our task is multi-class classification. In our case, we need repeat this three times.
>    For transforms of training data and test data, should we keep using the existing settings from DomainLab/examples/tasks/task_blood2.py?
> 
> Do you have any suggestions or ideas of next step?
Thanks for the hard work! 
1. I would suggest we use the easiest setting to have  something first, then we can discuss improvements. 
2. I guess maybe we can use a minimal configuration (e.g. removing some algorithms and hyper-parameters and don't use statistical repetition) to ensure we have something on Friday? 
@xinyuejohn , what do you think?

**Comment by xinyuejohn** [comment]
> 1. I would suggest we use the easiest setting to have  something first, then we can discuss improvements.
> 2. I guess maybe we can use a minimal configuration (e.g. removing some algorithms and hyper-parameters and don't use statistical repetition) to ensure we have something on Friday?
>    @xinyuejohn , what do you think?

@smilesun @rahulbshrestha 
I totally agree! I will talk to Rahul regarding this. Hopefully we will have something before Friday.

**Comment by schoersch** [comment]
@xinyuejohn @smilesun I see that it is nice to have something on Friday. That's why I moved the short yaml file of @xinyuejohn to `bloodcell_benchmark`.

On **this** branch, `BloodCell_yml`, @Car-la-F  and I were working on creating a yaml with all algorithms **for the final benchmark** so that we can start the actual benchmark as soon as first tests suggest that it will work.

**Comment by schoersch** [comment]
Also please note that there is still a second yaml file around for this: https://github.com/marrlab/DomainLab/blob/BloodCell_yml/examples/yaml/bloodcell_test.yaml

**Comment by smilesun** [comment]
@Car-la-F @schoersch @xinyuejohn @RahelehSalehi , hyper-parameters for DIAL also added here
https://github.com/marrlab/DomainLab/blob/master/domainlab/algos/trainers/args_dial.py

but maybe we don't add it to the benchmark yet before this Friday.

**Comment by schoersch** [comment]
@rahulbshrestha @xinyuejohn you can continue working on this branch... I'll make a separate one for denbi

@smilesun @Car-la-F @rahulbshrestha @xinyuejohn please make sure to pass `--keep-going` to snakemake. Otherwise it fully stops on the first failing job.

**Comment by schoersch** [comment]
@xinyuejohn @rahulbshrestha In case this helps you on the helmholtz cluster:

setting `dmem: True` on the config increases the ram usage a bit (of the cpu) but pushes the GPU usage to 100%

**Comment by schoersch** [comment]
This yaml file is also ported to all branches that need it, which should be helm_benchmark.

**Comment by schoersch** [comment]
@smilesun @Car-la-F @xinyuejohn @rahulbshrestha This branch can be deleted from my side. All changes are somewhere else...

**Pull request closed without merging**
