### PR TITLE
change to ruamel-yaml reader

### PR DESCRIPTION
**Pull request by Car-la-F**
I changed all the yaml reaing sections to use the ruamel package.

### CODE REVIEW

**Comment by Car-la-F** [comment]
@smilesun 

I guess pyyaml is the package which was used before I chnaged to ruamel. Shall we remove pyyaml from the requirements?

additionally, I added 

```
ruamel-yaml = "^0.17.32"
ruamel-yaml-clib = "^0.2.7"
```

to `pyproject.toml`. Is this correct to add the package as a requirement?

**Comment by Car-la-F** [comment]
will solve #429

**Comment by smilesun** [comment]
`./run_benchmark_standalone.sh examples/benchmark/demo_benchmark.yaml`
result in

Error in rule run_experiment:
    jobid: 0
    input: zoutput/benchmarks/demo_benchmark00/hyperparameters.csv
    output: zoutput/benchmarks/demo_benchmark00/rule_results/1.csv
```

RuleException:
TypeError in file /home/sunxd/domainlab/domainlab/exp_protocol/benchmark.smk, line 151:
can only concatenate str (not "int") to str
  File "/home/sunxd/domainlab/domainlab/exp_protocol/benchmark.smk", line 151, in __rule_run_experiment
  File "/home/sunxd/domainlab/domainlab/exp_protocol/run_experiment.py", line 131, in run_experiment
  File "/home/sunxd/domainlab/domainlab/compos/exp/exp_main.py", line 60, in execute
  File "/home/sunxd/anaconda3/lib/python3.9/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```

**Comment by smilesun** [comment]
> @smilesun
> 
> I guess pyyaml is the package which was used before I chnaged to ruamel. Shall we remove pyyaml from the requirements?
> 
> additionally, I added
> 
> ```
> ruamel-yaml = "^0.17.32"
> ruamel-yaml-clib = "^0.2.7"
> ```
> 
> to `pyproject.toml`. Is this correct to add the package as a requirement?

if we remove pyyaml, I got

```
./run_benchmark_standalone.sh examples/benchmark/demo_benchmark.yaml 
verbose log: zoutput/logs/2023-10-23_11-01-34.out
argument 2=
argument 2: DOMAINLAB_CUDA_START_SEED empty
argument 3: 
argument 3: DOMAINLAB_CUDA_HYPERPARAM_SEED empty, will set to 0
argument 4: NUMBER_GPUS=
argument 4: NUMBER_GPUS set to 1
argument 4: NUMBER_GPUS=1
Traceback (most recent call last):
  File "/home/sunxd/anaconda3/bin/snakemake", line 8, in <module>
    sys.exit(main())
  File "/home/sunxd/anaconda3/lib/python3.9/site-packages/snakemake/__init__.py", line 2671, in main
    config = parse_config(args)
  File "/home/sunxd/anaconda3/lib/python3.9/site-packages/snakemake/__init__.py", line 1000, in parse_config
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

**Comment by smilesun** [comment]
trying a fix here
https://github.com/marrlab/DomainLab/pull/585
and here
https://github.com/marrlab/DomainLab/pull/584

**Comment by smilesun** [comment]
fixed in [1aebf84](https://github.com/marrlab/DomainLab/commit/1aebf84ea2c61dc3820a06ac6f89ec93ebc9a674)
and commit b4b9ce66bad58310e3cae17564c218d84a4bd660
https://github.com/marrlab/DomainLab/commit/b4b9ce66bad58310e3cae17564c218d84a4bd660

**Pull request closed without merging**
