### PR TITLE
use task multiplier in abstract model only

### PR DESCRIPTION
**Pull request by smilesun**

### CODE REVIEW

**Review by e-dorigatti — APPROVED** [review]

**Comment by smilesun** [comment]
@e-dorigatti , test passed, the rest of CI is still running.

**Comment by smilesun** [comment]
I will merge it to fbopt before it goes into master

**Comment by smilesun** [comment]
@e-dorigatti , done

**Comment by e-dorigatti** [comment]
probably better to merge everything in fbopt for now. can you close this PR and the related issue then?

**Comment by smilesun** [comment]
i have merge it to fbopt already,  this PR is against master

**Comment by smilesun** [comment]
--- Logging error ---
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/runner/work/DomainLab/DomainLab/main_out.py", line 17, in <module>
    exp.execute()
  File "/home/runner/work/DomainLab/DomainLab/domainlab/compos/exp/exp_main.py", line 65, in execute
    flag_stop = self.trainer.tr_epoch(epoch)
  File "/home/runner/work/DomainLab/DomainLab/domainlab/algos/trainers/train_matchdg.py", line 48, in tr_epoch
    self.erm.tr_epoch(epoch)
  File "/home/runner/work/DomainLab/DomainLab/domainlab/algos/compos/matchdg_ctr_erm.py", line 76, in tr_epoch
    self.update_batch(epoch, batch_idx, x_e, y_e, d_e)
  File "/home/runner/work/DomainLab/DomainLab/domainlab/algos/compos/matchdg_ctr_erm.py", line 195, in update_batch
    logger.debug(f'class {y_c} with same class and different class: ',
Message: 'class 0 with same class and different class: '
Arguments: ('2 0',)
--- Logging error ---

**Comment by smilesun** [comment]
this error only touches master, should be irrelavent to fbopt, hopefully

**Pull request merged**
