### PR TITLE
Changed path from data to domainlab/zdata

### PR DESCRIPTION
**Pull request by MatteoWohlrapp**
Still needs testing of PACS tasks on server, but wanted to check if CI runs

### CODE REVIEW

**Comment by MatteoWohlrapp** [comment]
I compared the zdata and data folder; the only difference was from the test_parameter_samples.csv. I copied the content from the data folder, as the only code reference to that file pointed towards that folder.

**Comment by MatteoWohlrapp** [comment]
Tested on the cluster to run pacs job both within the repository and installed through tar. 
Should I publish it to Pypi?

**Comment by smilesun** [comment]
This PR deleted the whole /data folder?  but no data is added  to /domainlab/zdata or I did that already in previous commit so we won't lose any data if merging this PR? 

image

**Comment by MatteoWohlrapp** [comment]
I checked the difference between the data and zdata folder with `diff`, which tells you whether files exist in one directory but not the other, or if files with the same name have different sizes or timestamps. The only difference was from the test_parameter_samples.csv, which I copied from the data folder to zdata.

**Comment by smilesun** [comment]
great, thanks!

**Comment by smilesun** [comment]
yes, please update pypi then! @MatteoWohlrapp

**Pull request merged**
