### PR TITLE
image generation from a mk_task_folder implemented in a test function…

### PR DESCRIPTION
**Pull request by smilesun**
… to have a easy executable prototype.

function can be found in test_taskfolder_dset_extraction.py

### CODE REVIEW

**Comment by smilesun** [comment]
Good job!

1. could you two also add how to use this feature to the documentation?

For example, you can edit this file to explain to the user how to use this sanity check?
2. could you make the codacy pass? obviously you introduced some code not up to standard of code style
3. why your code drops the coverage? have you tested each line of your code?

**Comment by Car-la-F** [comment]
@smilesun,
thank you for fixing the style issues. 
I added a test to the code, fixed the remaining style issues and added an example to the documentation using the sanity check with an user specified sample number. 

The code should be finished now :)

**Comment by smilesun** [comment]
@Car-la-F great job!  I will review this together with @aliechoes since he proposed the corresponiding issue.

**Comment by smilesun** [comment]
@Car-la-F , I runned the example you offered, 
`python main_out.py --te_d 0 1 2 --tr_d 3 7 --task=mini_vlcs --aname=diva --nname=conv_bn_pool_2 --nname_dom=conv_bn_pool_2 --gamma_y=7e5 --gamma_d=1e5 --san_check --san_num=8 
`
and I got the following error:
```
/home/sunxd/anaconda3/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: /home/sunxd/anaconda3/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
  warn(f"Failed to load image Python extension: {e}")
/home/sunxd/DomainLab/domainlab/arg_parser.py:153: UserWarning: no algorithm conf specified, going to use default
  warnings.warn("no algorithm conf specified, going to use default")
Traceback (most recent call last):
  File "/home/sunxd/DomainLab/main_out.py", line 8, in <module>
    exp = Exp(args=args)
  File "/home/sunxd/DomainLab/domainlab/compos/exp/exp_main.py", line 28, in __init__
    self.dataset_sanity_check(args, args.san_num)
  File "/home/sunxd/DomainLab/domainlab/compos/exp/exp_main.py", line 69, in dataset_sanity_check
    self.task.init_business(args)
  File "/home/sunxd/DomainLab/domainlab/tasks/task_folder_mk.py", line 57, in init_business
    super().init_business(args)
  File "/home/sunxd/DomainLab/domainlab/tasks/b_task.py", line 54, in init_business
    list_domain_tr, list_domain_te = self.get_list_domains_tr_te(args.tr_d, args.te_d)
  File "/home/sunxd/DomainLab/domainlab/tasks/a_task.py", line 156, in get_list_domains_tr_te
    list_domain_tr = parse_domain_id(tr_id, list_domains)
  File "/home/sunxd/DomainLab/domainlab/tasks/a_task.py", line 28, in parse_domain_id
    list_domains_subset.append(list_domains[int(ele)])
IndexError: list index out of range
```
does the example you offered work on your machine?

**Comment by Car-la-F** [comment]
> @Car-la-F , I runned the example you offered, `python main_out.py --te_d 0 1 2 --tr_d 3 7 --task=mini_vlcs --aname=diva --nname=conv_bn_pool_2 --nname_dom=conv_bn_pool_2 --gamma_y=7e5 --gamma_d=1e5 --san_check --san_num=8 ` and I got the following error:
> 
> ```
> /home/sunxd/anaconda3/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: /home/sunxd/anaconda3/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
>   warn(f"Failed to load image Python extension: {e}")
> /home/sunxd/DomainLab/domainlab/arg_parser.py:153: UserWarning: no algorithm conf specified, going to use default
>   warnings.warn("no algorithm conf specified, going to use default")
> Traceback (most recent call last):
>   File "/home/sunxd/DomainLab/main_out.py", line 8, in <module>
>     exp = Exp(args=args)
>   File "/home/sunxd/DomainLab/domainlab/compos/exp/exp_main.py", line 28, in __init__
>     self.dataset_sanity_check(args, args.san_num)
>   File "/home/sunxd/DomainLab/domainlab/compos/exp/exp_main.py", line 69, in dataset_sanity_check
>     self.task.init_business(args)
>   File "/home/sunxd/DomainLab/domainlab/tasks/task_folder_mk.py", line 57, in init_business
>     super().init_business(args)
>   File "/home/sunxd/DomainLab/domainlab/tasks/b_task.py", line 54, in init_business
>     list_domain_tr, list_domain_te = self.get_list_domains_tr_te(args.tr_d, args.te_d)
>   File "/home/sunxd/DomainLab/domainlab/tasks/a_task.py", line 156, in get_list_domains_tr_te
>     list_domain_tr = parse_domain_id(tr_id, list_domains)
>   File "/home/sunxd/DomainLab/domainlab/tasks/a_task.py", line 28, in parse_domain_id
>     list_domains_subset.append(list_domains[int(ele)])
> IndexError: list index out of range
> ```
> 
> does the example you offered work on your machine?

There was a mistake in the setup of the example. I fixed it, it should work now.

**Comment by Car-la-F** [comment]
Each of the .jpg files includes a maximum of 8 images. Some of them contain less, thats the case if the whole dataset has less then 8 images.

Maybe I should set down --san_num to 2 as we don't have this case then where one dataset has less than 2 images

**Comment by smilesun** [comment]
Thanks for the reply. 

https://github.com/marrlab/DomainLab/tree/master/data/vlcs_mini/caltech/auto

1. The dataset contains more than 8 images?
2. there are only 2 classes being sampled?

**Comment by aliechoes** [comment]
from my side it seems ok

**Comment by smilesun** [comment]
@Car-la-F , actually even i change the number

`python main_out.py --te_d=caltech --task=mini_vlcs --debug --bs=2 --aname=diva --nname=alexnet --npath_dom=examples/nets/resnet.py --gamma_y=7e5 --gamma_d=1e5  --san_check --san_num=3`

i only got 2 images per domain, and in fact there are 5 classes in each domain.

Please also see my comments above.

**Comment by Car-la-F** [comment]
> Thanks for the reply.
> 
> https://github.com/marrlab/DomainLab/tree/master/data/vlcs_mini/caltech/auto
> 
>     1. The dataset contains more than 8 images?
> 
>     2. there are only 2 classes being sampled?

According to:

1. yes that's true. I was too sloppy in my reply. I meant that some class-domain combination do have less than 8 images. For example for _domain = sun_ and _class = sofa/chair_ there are only 4 images. In this case the output will only contain these 4 images in `sun/chair.jpg`. For _domain = sun_ and _class = vehicle/car_ the dataset contains 9 images, hence in `sun/car.jpg` it will only show 8 of these 9 images.

2. In the description of the mini_vlcs task it is defined to only use two classes, `chair` and `car`. This classes should be represented in the output. Other classes are not represented.

**Pull request merged**
